# Generated by Django 5.2.8 on 2025-11-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_created_otpcode_created_at_otpcode_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.IntegerField(),
        ),
    ]
